language: python

python:
  - "3.6"

services:
  - postgresql

cache:
  - pip

install:
  - echo "ENV=travis" > .env
  - make install-dev

before_script:
  - psql -c "CREATE ROLE {{cookiecutter.project_name}} CREATEDB LOGIN PASSWORD '{{cookiecutter.project_name}}';" -U postgres
  - psql -c "CREATE DATABASE {{cookiecutter.project_name}};" -U postgres

script: make test

after_success:
- bash <(curl -s https://codecov.io/bash)
