version: '2'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER={{cookiecutter.project_name}}
      - POSTGRES_PASSWORD={{cookiecutter.project_name}}
